### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by andrew-scoppa** [gh-mentor/wa-captions#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Participating and @mentions' or 'Ignoring' option.

**Comment by andrew-scoppa** [comment]
#### Please say something to be added as a collaborator. 😄 

This will do the following:

- Create a file with your handle.
- Add you as a collaborator with 'write' role

Hey @AAugustine check this out: [Probot App Builder](https://probot.github.io/docs/)

**Comment by Jamie42** [comment]
### Hi Andrew, Please add me to list of collaborators. 🍉

**Comment by jlee253** [comment]
Hello, please add Jordan as a collaborator.

**Comment by Theseawolfs** [comment]
Please, say something to be added as a collaborator :)

This will do the following
-Create a file with your handle.
-Add you as a collaborator with write role
 Hey @githubteacher  check this  out : [ Probot App Builder[ (https://probot.github.io/docs/ )]

**Comment by jwsmith95** [comment]
Adding a comment...

**Comment by sjdor140** [comment]
Hello, Please add me as a Collaborator.

**Comment by quynhchi9** [comment]
I'm listening
